name: Release

on:
  push:
    tags:
      - "**"

env:
  CF_API_KEY: ${{ secrets.CF_API_KEY }}
  WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
  GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    environment: Default
    steps:
      - name: Clone project
        uses: actions/checkout@v1
        with: { fetch-depth: 20 }
      - name: Package and release
        uses: BigWigsMods/packager@v2
